### ISSUE TITLE
seems calculation not correct

### ISSUE THREAD

**Issue by SaddamBInSyed** [sriramsk1999/gestures-mediapipe#1]
@sriramsk1999 

thanks for the work.

Is this code working fine for you?
seems mouse pointer calculation is not correct method.

thoughts..

**Comment by sriramsk1999** [comment]
Hello, yes it is working fine for me. 
Could you describe the issues you are facing and why you think the mouse pointer calculation method is incorrect?

**Comment by SaddamBInSyed** [comment]
@sriramsk1999 

Hi there.

Actually I have my python ( [mediapipe based](https://github.com/metalwhale/hand_tracking)) app to detect hand gesture.

I just followed your code and passed the x,y of the index finger to your calculation.

but my mouse is not moving properly.

will it work in this way.?
did you try this on win10 os?

advise please.

**Comment by sriramsk1999** [comment]
Firstly, please make sure you are referring to the latest version of the code. This is a work in progress and frequent code changes will be taking place. 

Secondly, what do you mean by "not moving properly"? Is there a delay in the mouse movement? Does it move in random directions? Does it not move at all? Please describe your issue more accurately, or better yet, post a small video showing the problem.

I have not tested this on Windows. The mouse control code is fairly straightforward and uses `pyautogui` to move the mouse. Perhaps you can check if that library is working as expected on Windows with a simple program.

**Comment by SaddamBInSyed** [comment]
@sriramsk1999 ,

"not moving properly" means - 
my cursor always going to top left posiiton even though i drag to dottom.

pyautogui  - works perfect with test app.
I am using autopy for even smooth move. but the problem on the cursor movement.

**Comment by sriramsk1999** [comment]
If the cursor is going to the top left (that is, (0,0)) that means that either the hand isn't detected, or the wrong coordinates are being fed. 

Please print the coordinates while running the code and make sure everything is as expected. As shown in [this image](https://lh5.googleusercontent.com/WIIe0qzkGp0RaqfsXUAa8deV1gEk4iVOG8RJc0R6DVH-LKl2bzyTdBHYcG-j45-h2KZUOdEtmaHTj-6pKANx3smSmvn8QcLdyRGhRDM-P89BI8RIb_Z23M6elNK0gY7XF0Qau7Le), the tip of the index finger should correspond to LM8, the ninth landmark being printed.

**Comment by SaddamBInSyed** [comment]
@sriramsk1999 
coordinates are correct I printer. 
it is not (0, 0) but like the left position of the screen. anyhow I will try again now and update you.

also, I am going to try this in ubuntu(vmware). 
should I need the mediapipe installation as stated [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu)
or only bazel enough to run the script.?

please advise

**Comment by sriramsk1999** [comment]
The mediapipe installation is necessary, the bazel executable largely depends on mediapipe.

**Comment by SaddamBInSyed** [comment]
![image](https://user-images.githubusercontent.com/10062672/85225409-12f13580-b3e2-11ea-9ed1-7720f8f260f0.png)


above is the result.

red - my index finger x,y
green - after your calculation method.

    index_pointer = landmarks[8]['x'], landmarks[8]['y'], landmarks[8]['z']

    # Screen resolution
    resolution = pyautogui.size().width, pyautogui.size().height
    scaled_pointer = resolution[0]*index_pointer[0], resolution[1]*index_pointer[1]

    pointer_buffer[ITER_COUNT%5] = scaled_pointer
    actual_pointer = get_avg_pointer_loc(pointer_buffer)

printing (actual_pointer )

so, it seems I am passing the index finger x, y, right but calculation giving error result.

but it is weird for me how it is working for your system.???

**Comment by sriramsk1999** [comment]
Alright so, my code expects normalized coordinates, in the range of (0,0) to (1,1), so that is the source of the issue. *All the landmarks being used **must** be normalized.* I'm not sure in what format [metalwhale's repo](https://github.com/metalwhale/hand_tracking) outputs the coordinates, but if you normalize it, that should solve the problem.  

On another note, the numbers aren't adding up. Looking at the printed numbers, it looks like you have a 4k screen with resolution (3840, 2160) but dividing the numbers printed gives me a resolution of (384, 216). I'm not sure why that has happened but it is something to keep an eye on.

**Comment by SaddamBInSyed** [comment]
@sriramsk1999 
my screen res: 1920 * 1080
my cam window  is = 640 * 480. ( so my index finger coordinates ranging bw (0, 0) to (639, 479).

the ( metalwhale's repo) just giving me,  my app window coordinates (in my case ranging bw (0, 0) to (640, 480).) so that I can plot the hand key points on the screen.

if you are using the normalized value then how you are plotting your hand key points on the screen?

if you have any known calculation then you can share with me here.

**Comment by sriramsk1999** [comment]
Ah okay, so normalizing the coordinates is a simple task. 

All the calculation is in the code you've shown itself :)
The normalized coordinates are multiplied by your screen's resolution, effectively projecting your hand's position in the webcam window as the position of the cursor on your screen. 

If `pyautogui.size().width, pyautogui.size().height` returns (1920, 1080) then after normalizing the coordinates, I believe the mouse tracking will work.

**Comment by SaddamBInSyed** [comment]
@sriramsk1999 

Since your code only work with normalized value so How do I get/convert my key points to Normalized value.?

any idea.

**Comment by sriramsk1999** [comment]
Its quite simple :), just divide the output coordinates by the maximum possible value, which from what you said, is 640 and 480. Hope that clears everything up.

**Comment by SaddamBInSyed** [comment]
@sriramsk1999 

thanks for your help. but my hand keypoints are not stable as compared to your demo. 
so i trying to setup linux environment with your code.
I will update the status here

**Comment by sriramsk1999** [comment]
Closing this as issue has been solved.
