### ISSUE TITLE
Installation steps 

### ISSUE THREAD

**Issue by SaddamBInSyed** [sriramsk1999/gestures-mediapipe#2]
@sriramsk1999 
Since I from windows user, 
Could you please paste your terminal cmd here.

I followed the mediapipe installation and the Hello world app is working fine.

now I am struggle with the below steps,
"
As well as mediapipe's own requirements, there a few other things required for this project.
ZeroMQ (along with cppzmq and pyzmq)
The zeromq library (libzmq.so) must be symlinked into this directory. The header only C++ binding cppzmq must also be installed and its header (zmq.hpp) symlinked into the working directory. The python module pyzmq must also be installed for python to read the keypoints being sent.
"

thanks

**Comment by sriramsk1999** [comment]
I cannot simply paste terminal commands here. I am not aware of how your system is configured and things might break with the wrong commands. Please refer to the installation pages of the respective tools and install them onto your system.

After installation, if my code does not work, I will be glad to help you. In addition, please refrain from mentioning me in every comment as it clutters up my notifications.

**Comment by SaddamBInSyed** [comment]
all done.

but not as smooth as your demo. maybe I need GPU to get rid of keypoints flickering.

thanks.

**Comment by sriramsk1999** [comment]
Glad to hear it :) Yes, it is quite choppy with just CPU.
